db:
  uri: "postgresql+psycopg2://${DB_NAME}:${DB_PASS}@db/${DB_USER}"
asterisk:
  uri: "mysql+pymysql://${ASTERISK_USER}:${ASTERISK_PASS}@${ASTERISK_HOST}:${ASTERISK_DB_PORT}/${ASTERISK_DB}?charset=utf8mb4"
  host: "${ASTERISK_HOST}"
  port: "${ASTERISK_PORT}"
jwt:
  secret: "${SECRET_KEY}"
ssh:
  user: "10.3.0.48"
  pass: "LexP@ssw0rd_1"
hyperscript:
  uri: ""
  port: ""