db:
  uri: "postgresql+psycopg2://${DB_NAME}:${DB_PASS}@db/${DB_USER}"
asterisk:
  uri: "mysql+pymysql://${ASTERISK_USER}:${ASTERISK_PASS}@${ASTERISK_HOST}:${ASTERISK_DB_PORT}/${ASTERISK_DB}?charset=utf8mb4"
  host: "${ASTERISK_HOST}"
  port: "${ASTERISK_PORT}"
jwt:
  secret: "${SECRET_KEY}"
asterisk_ssh:
  host: "10.3.0.48"
  port: 22
  password: "LexP@ssw0rd_1"
  user: "root"
  paths:
    ivr: "/etc/asterisk/queue_ivrs/"

hyperscript:
  uri: "${HYPERSCRIPT_HOST}:${HYPERSCRIPT_PORT}"