db:
  uri: "postgresql+psycopg2://${DB_NAME}:${DB_PASS}@10.3.0.48:5432/${DB_USER}"
asterisk:
  uri: "mysql+pymysql://${ASTERISK_USER}:${ASTERISK_PASS}@${ASTERISK_HOST}:${ASTERISK_DB_PORT}/${ASTERISK_DB}?charset=utf8mb4"
  host: "${ASTERISK_SETTINGS_HOST}"
  port: "${ASTERISK_PORT}"
jwt:
  secret: "${SECRET_KEY}"
asterisk_ssh:
  host: "10.3.0.48"
  port: 22
  password: "LexP@ssw0rd_1"
  user: "root"
  paths:
    ivr: "/etc/asterisk/queue_ivrs/"

hyperscript:
  uri: "${HYPERSCRIPT_HOST}:${HYPERSCRIPT_PORT}"

analytics:
  disposal:
    break:
      description: 'Перерыв'
      color: '#1890FF'
    break_lunch:
      description: 'Перерыв (обед)'
      color: '#096DD9'
    break_toilet:
      description: 'Перерыв (туалет)'
      color: '#40A9FF'
    break_training:
      description: 'Перерыв (обучение)'
      color: '#46D3C2'
    ready:
      description: 'Готов'
      color: '#B9DD79'
  ant:
    precall:
      description: 'Время предвызовной обработки'
      color: '#B9DD79'
    aftercall:
      description: 'Время поствызывной обработки'
      color: '#FD7077'
    externalcall:
      description: 'Время разговора'
      color: '#46D3C2'
    callwaiting:
      description: 'Ожидание ответа абонента'
      color: '#40A9FF'
  call:
    ANSWERED:
      description: 'Принято'
      color: '#B9DD79'
    'NO ANSWER':
      description: 'Пропущено'
      color: '#C78FFE'
    BUSY:
      description: 'Переведено'
      color: '#51D5C6'
